name: A workflow
on: 
  push:
      branches:
            - master
jobs:
    Docker-Build-Push:
        name: hello word
        runs-on: ubuntu-latest
        steps:
           - name: check out res code
             uses: actions/checkout@v2
           - name: Get latest commit on release branch
             run: |
                  echo "LATEST_RELEASE_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV

           - name: Get commit list on dev branch
             run: |
                  echo "DEV_COMMIT_LIST=$(git log --pretty=format:%H origin/dev)" >> $GITHUB_ENV

           - name: Check for new commits in dev branch
             run: |
                 LATEST_RELEASE_COMMIT=${LATEST_RELEASE_COMMIT}
                 DEV_COMMIT_LIST=${DEV_COMMIT_LIST}
                 if echo "$DEV_COMMIT_LIST" | grep -q "$LATEST_RELEASE_COMMIT"; then
                    echo "Latest release commit is in dev branch. Proceeding with workflow."
                 else
                    echo "Latest release commit is not in dev branch. Skipping workflow."
                    exit 0;
                 fi
           - name: Set up Docker Buildx
             uses: docker/setup-buildx-action@v3
           - name: Login to Docker Hub
             uses: docker/login-action@v3
             with:
                   username: ${{ secrets.DOCKER_USERNAME }}
                   password: ${{ secrets.DOCKER_PASSWORD }}
         

        
        