name: A workflow
on: 
  push:
      branches:
            - master
jobs:
    Docker-Build-Push:
        name: hello word
        runs-on: ubuntu-latest
        steps:
           - name: check out res code
             uses: actions/checkout@v2
           - name: Get previous test commit 
             run: |
                  PREVIOUS_TEST_COMMIT=$(git rev-parse origin/test)
                  echo "::set-output name=previous_test_commit::$PREVIOUS_TEST_COMMIT"
                  id: get_previous_test_commit
           - name: Compare code     
             run: |
                  PREVIOUS_TEST_COMMIT="${{ steps.get_previous_test_commit.outputs.previous_test_commit }}"
                  CHANGED_FILES=$(git diff --name-only $PREVIOUS_TEST_COMMIT HEAD)
                  echo "Changed files: $CHANGED_FILES"
           - name: Check for new commits
             run: |
                  PREVIOUS_TEST_COMMIT="${{ steps.get_previous_test_commit.outputs.previous_test_commit }}"
                  CURRENT_TEST_COMMIT=$(git rev-parse origin/test)
                  if [ "$PREVIOUS_TEST_COMMIT" != "$CURRENT_TEST_COMMIT" ]; then
                    echo "New commits in test branch. Proceeding with workflow."
                  else
                    echo "No new commits in test branch. Skipping workflow."
                  exit 0
                  fi

        
        