name: A workflow
on: 
  push:
      branches:
            - master
jobs:
    Docker-Build-Push:
        name: hello word
        runs-on: ubuntu-latest
        steps:
           - name: check out res code
             uses: actions/checkout@v2
           - name: docker image build
             run: docker build -t clydev/demo:v1.0.3 .
           - name: list docker image
             run: docker image ls
           - name: dockerhub login
             run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
           - name: push to dockerbub
             run: docker  push clydev/demo:v1.0.3

        
        