name: A workflow
on: push
jobs:
    Docker-Build-Push:
        name: hello word
        runs-on: ubuntu-latest
        steps:
           - name: check out res code
             uses: actions/checkout@v2
           - name: docker image build
             run: docker build -t demo:v1.0.1 .
           - name: list docker image
             run: docker image ls

        
        