name: a demo

on:
  push:
       branches:
              - dev
jobs:
    Docker-Build-Push:
        name: hello word
        runs-on: ubuntu-latest
        steps:
            - name: checkout out res code
              uses: actions/checkout@v2
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: dockerhud login and push
              run: /
                   docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
                   docker buildx ls
                   docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 -t clydev/demo:1.0.5 .

